# Generated by Django 3.2.9 on 2021-11-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_no', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('items_price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='invoices',
            name='invoice_customer_name',
            field=models.CharField(default='Customer Name Undefined', max_length=100),
        ),
        migrations.AddField(
            model_name='invoices',
            name='invoice_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='invoice_status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending', 'pending'), ('overdue', 'overdue'), ('cancelled', 'cancelled')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.invoices')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.items')),
            ],
        ),
    ]
