# Generated by Django 3.2.9 on 2021-11-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211106_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
