# Generated by Django 3.2.9 on 2021-11-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_invoices_invoice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='items_price',
            new_name='item_price',
        ),
    ]
