# Generated by Django 3.2.9 on 2021-11-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_items_price_items_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='invoice_customer_email',
            field=models.EmailField(default='shubham7811@yahoo.com', max_length=254),
        ),
    ]
