import smtplib
import base64

def createInvoicePDF():
    filename = ''
    return filename

def sendMail(invoice_id, company_name, invoice_items_list, customer_name, customer_email_id, total_amount):
    # filename = createInvoicePDF()
    filename = 'C:\\Users\\Shubham\\Pictures\\img5.jpg'
    fo = open(filename, "rb")
    filecontent = fo.read()
    encodedcontent = base64.b64encode(filecontent)
    marker = "AUNIQUEMARKER"
    
    gmail_user = 'techcse2020@bpitindia.com'
    gmail_password = 'Bpit@1234'
    sent_from = gmail_user
    to = [customer_email_id]
    subject = 'Form registration successful'
    body = '''
            Hi, {customer_name} 
            Your invoice for amount {total_amount} is generated by {company_name}
            Kindly pay the pending amount using this link: https://url/invoice/{invoice_id}
            For the detailed invoice you can download the attached pdf.
        '''.format(customer_name=customer_name,total_amount=total_amount,company_name=company_name,invoice_id=invoice_id)
    # Define the attachment section
    part3 = '''
            Content-Type: multipart/mixed; name=\"%s\"
            Content-Transfer-Encoding:base64
            Content-Disposition: attachment; filename=%s

            %s
            --%s--
        ''' %(filename, filename, encodedcontent, marker)

    email_text = """
        From: %s
        To: %s
        Subject: %s

        %s
        """ % (sent_from, ", ".join(to), subject, body+part3)

    try:
        smtp_server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        smtp_server.ehlo()
        smtp_server.login(gmail_user, gmail_password)
        smtp_server.sendmail(sent_from, to, email_text)
        smtp_server.close()
        print ("Email sent successfully!")
    except Exception as ex:
        print("Something went wrong")

# https://www.tutorialspoint.com/python/python_sending_email.htm

def main():
    gmail_user = 'techcse2020@bpitindia.com'
    gmail_password = 'Bpit@1234'

    sent_from = gmail_user
    to = ['shubham220901@gmail.com']
    subject = 'Form registration successful'
    body = '''
        Hi, thank you for registering
        Please join this telegram group for future updates and notifications
        https://t.me/joinchat/17V9iyzIYIRiN2Rl
    '''

    email_text = """
    From: %s
    To: %s
    Subject: %s

    %s
    """ % (sent_from, ", ".join(to), subject, body)

    try:
        smtp_server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        smtp_server.ehlo()
        smtp_server.login(gmail_user, gmail_password)
        smtp_server.sendmail(sent_from, to, email_text)
        smtp_server.close()
        print ("Email sent successfully!")
    except Exception as ex:
        print("Something went wrong")

if __name__ == '__main__':
    main()